### ISSUE TITLE
Android: Push notifications 60sec delay when app is terminated (task manager swipe)

### ISSUE THREAD

**Issue by Spinaker70** [ben-xD/push#36]
Android 9

From ADB logcat:
------------------------
```
09-14 10:51:30.655  2061  2077 D Boost   : hostingType=broadcast, hostingName=ru.neotelecom.uscs/uk.orth.push.FirebaseMessagingReceiver, callerPackage=com.google.android.gms, isSystem=true, isBoostNeeded=false.
09-14 10:51:30.657  2061  2077 I ActivityManager: Start proc 2058:ru.neotelecom.uscs/u0a427 for broadcast ru.neotelecom.uscs/uk.orth.push.FirebaseMessagingReceiver caller=com.google.android.gms
09-14 10:51:36.997  2058  2187 D ProfileInstaller: Skipping profile installation for ru.neotelecom.uscs


09-14 10:52:30.619  2061  2075 W BroadcastQueue: Receiver during timeout of BroadcastRecord{414d9d7 u0 com.google.android.c2dm.intent.RECEIVE} : ResolveInfo{d32f14e ru.neotelecom.uscs/uk.orth.push.FirebaseMessagingReceiver m=0x108000}
09-14 10:52:30.696  2061  2075 I ActivityManagerServiceInjector: finish silent ANR: ProcessRecord{a8a72c4 2058:ru.neotelecom.uscs/u0a427}
09-14 10:52:30.696  2061  2075 I ActivityManager: Killing 2058:ru.neotelecom.uscs/u0a427 (adj 0): bg anr
09-14 10:52:30.736  8622  8622 W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=ru.neotelecom.uscs (has extras) }
09-14 10:52:30.828  2286  2286 D StatusBar: onNotificationPosted key=0|ru.neotelecom.uscs|0|FCM-Notification:357331374|10427 isUpdate=false
09-14 10:52:30.845  2286  2286 D StatusBar: peeking: miui permission allows: 0|ru.neotelecom.uscs|0|FCM-Notification:357331374|10427
09-14 10:52:31.005  2286  2286 D StatusBar: peeking: miui permission allows: 0|ru.neotelecom.uscs|0|FCM-Notification:357331374|10427
09-14 10:52:31.040  2286  2286 D StatusBar: update app badge num: ru.neotelecom.uscs/,num=1,isAllowed=true,userId=0
09-14 10:52:31.042  2504  2624 I Launcher.ApplicationsMessage: update ru.neotelecom.uscs/ to 1

```

**Comment by Spinaker70** [comment]
09-14 11:08:22.502  2061  2077 D Boost   : hostingType=broadcast, hostingName=ru.neotelecom.uscs/uk.orth.push.FirebaseMessagingReceiver, callerPackage=com.google.android.gms, isSystem=true, isBoostNeeded=false.
09-14 11:08:22.506  2061  2077 I ActivityManager: Start proc 6408:ru.neotelecom.uscs/u0a427 for broadcast ru.neotelecom.uscs/uk.orth.push.FirebaseMessagingReceiver caller=com.google.android.gms

09-14 11:09:22.450  2061  2075 W BroadcastQueue: Receiver during timeout of BroadcastRecord{edc5e04 u0 com.google.android.c2dm.intent.RECEIVE} : ResolveInfo{2433531 ru.neotelecom.uscs/uk.orth.push.FirebaseMessagingReceiver m=0x108000}
09-14 11:09:22.536  2061  2075 I ActivityManagerServiceInjector: finish silent ANR: ProcessRecord{3916fed 6408:ru.neotelecom.uscs/u0a427}
09-14 11:09:22.536  2061  2075 I ActivityManager: Killing 6408:ru.neotelecom.uscs/u0a427 (adj 0): bg anr
09-14 11:09:22.579  8622  8622 W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=ru.neotelecom.uscs (has extras) }

**Comment by bull-xu** [comment]
We have the same ANR issue:

```
main (native):tid=1 systid=32665 
#00 pc 0x4d820 libc.so (syscall + 32)
#01 pc 0x45a0c libc.so (scudo::SizeClassAllocatorLocalCache<scudo::SizeClassAllocator64<scudo::AndroidConfig> >::refill(scudo::SizeClassAllocatorLocalCache<scudo::SizeClassAllocator64<scudo::AndroidConfig> >::PerClass*, unsigned long) + 180)
#02 pc 0x42dbc libc.so (scudo::Allocator<scudo::AndroidConfig, &(scudo_malloc_postinit)>::allocate(unsigned long, scudo::Chunk::Origin, unsigned long, bool) + 388)
#03 pc 0x434d4 libc.so (scudo_malloc + 36)
#04 pc 0x3dcdc libc.so (malloc + 36)
#05 pc 0x8b15ec libGLES_mali.so (cframe_manager_new + 44)
#06 pc 0x81a784 libGLES_mali.so (gles_surface_converter_create + 68)
#07 pc 0x819968 libGLES_mali.so (gles_surface_init + 16)
#08 pc 0x7c82d0 libGLES_mali.so (gles_context_new + 2144)
#09 pc 0x8619a4 libGLES_mali.so (eglCreateContext + 1316)
#10 pc 0x2a2fc libEGL.so (android::eglCreateContextImpl(void*, void*, void*, int const*) + 196)
#11 pc 0x36c858 split_config.arm64_v8a.apk!libflutter.so + 15458304
#12 pc 0x36e650 split_config.arm64_v8a.apk!libflutter.so + 15458304
#13 pc 0x65bce8 split_config.arm64_v8a.apk!libflutter.so + 15458304
#14 pc 0x65b314 split_config.arm64_v8a.apk!libflutter.so + 15458304
#15 pc 0x65a9e0 split_config.arm64_v8a.apk!libflutter.so + 15458304
#16 pc 0x377730 split_config.arm64_v8a.apk!libflutter.so + 15458304
       at io.flutter.embedding.engine.FlutterJNI.nativeAttach(FlutterJNI.java)
       at io.flutter.embedding.engine.FlutterJNI.performNativeAttach(FlutterJNI.java)
       at io.flutter.embedding.engine.FlutterJNI.attachToNative(FlutterJNI.java)
       at io.flutter.embedding.engine.FlutterEngine.attachToJni(FlutterEngine.java)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java)
       at uk.orth.push.BackgroundFlutterAppLauncher.<init>(BackgroundFlutterAppLauncher.java)
       at uk.orth.push.FirebaseMessagingReceiver.sendMessageToFlutterApplication(FirebaseMessagingReceiver.java)
       at uk.orth.push.FirebaseMessagingReceiver.onReceive(FirebaseMessagingReceiver.java)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4843)
       at android.app.ActivityThread.access$1800(ActivityThread.java:315)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2297)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by Spinaker70** [comment]
Looks like the project is dead.
I'm going back to firebase_messaging
​

**Comment by ben-xD** [comment]
Okay, sure. The issue here doesn't contain enough information to help you. I also have limited time now.

PS: the project is not dead, I don't have the time to give free support or features right now. The existing features work.

**Comment by maziac** [comment]
Hi,
I would really like to use the push package. it is great.
However, I notice the same/mentioned delay of up to one minute or so when the app is terminated.
Is there something to do about?
